In [189]:
from tensorflow.keras.models import load_model
import pickle
import pandas as pd 
import tensorflow as tf
import numpy as np

In [190]:
with open('label_encoder.pkl','rb') as file:
    label= pickle.load(file)

In [192]:
with open('one_Hot_Encoder.pkl','rb') as file:
    onehot=pickle.load(file)

In [193]:
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

In [194]:
model=load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [195]:
user={'Pclass':3,'Sex':'female','SibSp':'1','Parch':1,'Fare':11,'Embarked':'Queenstown'}

In [196]:
user=pd.DataFrame([user])

In [197]:
user

   Pclass     Sex SibSp  Parch  Fare    Embarked
0       3  female     1      1    11  Queenstown

In [198]:
user['Sex']=label.transform(user['Sex'])

In [199]:
user

   Pclass  Sex SibSp  Parch  Fare    Embarked
0       3    0     1      1    11  Queenstown

In [200]:
embarked=onehot.transform(user[['Embarked']])

In [201]:
embarked=pd.DataFrame(embarked,columns=onehot.get_feature_names_out())

In [202]:
embarked

   Embarked_Chebourge  Embarked_Queenstown  Embarked_Southampton
0                 0.0                  1.0                   0.0

In [203]:
user=pd.concat([user.drop(columns=['Embarked']),embarked],axis=1)

In [204]:
user

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourge,Embarked_Queenstown,Embarked_Southampton
0,3,0,1,1,11,0.0,1.0,0.0

In [205]:
user[['Pclass', 'SibSp', 'Parch', 'Fare']] = scaler.transform(
    user[['Pclass', 'SibSp', 'Parch', 'Fare']]
)

In [215]:
y=model.predict(user)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step

In [216]:
y=y[0][0]

In [218]:
y

np.float32(nan)