In [4]:
import pandas as pd
import numpy as np

In [5]:
data=pd.read_csv('huge_1M_titanic.csv')
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1310,1,1,"Name1310, Miss. Surname1310",female,NaN,0,0,SOTON/O2 3101272,76.760165,NaN,C
1,1311,0,3,"Name1311, Col. Surname1311",male,29.0,0,0,223596,10.193097,NaN,S
2,1312,0,3,"Name1312, Mr. Surname1312",male,20.0,0,0,54636,12.029416,C83,C
3,1313,0,3,"Name1313, Mr. Surname1313",male,27.0,0,0,PC 17760,13.429448,NaN,S
4,1314,0,3,"Name1314, Mr. Surname1314",male,32.0,0,0,364512,4.840769,E33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1001305,0,2,"Name1001305, Mr. Surname1001305",male,27.0,0,0,244358,26.196512,NaN,S
999996,1001306,1,1,"Name1001306, Miss. Surname1001306",female,33.0,0,0,349221,102.555248,NaN,S
999997,1001307,0,3,"Name1001307, Mr. Surname1001307",male,NaN,1,0,PC 17601,8.274807,NaN,S
999998,1001308,0,2,"Name1001308, Mr. Surname1001308",male,35.0,1,0,112050,0.000000,B102,S
999999,1001309,1,1,"Name1001309, Miss. Surname1001309",female,37.0,1,0,28403,57.720316,NaN,S

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   PassengerId  1000000 non-null  int64
 1   Survived     1000000 non-null  int64
 2   Pclass       1000000 non-null  int64
 3   Name         1000000 non-null  str
 4   Sex          1000000 non-null  str
 5   Age          801400 non-null   float64
 6   SibSp        1000000 non-null  int64
 7   Parch        1000000 non-null  int64
 8   Ticket       1000000 non-null  str
 9   Fare         1000000 non-null  float64
 10  Cabin        229805 non-null   str
 11  Embarked     997760 non-null   str
dtypes: float64(2), int64(5), str(5)
memory usage: 132.6 MB

In [7]:
data.isnull().sum()

PassengerId         0
Survived            0
Pclass              0
Name                0
Sex                 0
Age            198600
SibSp               0
Parch               0
Ticket              0
Fare                0
Cabin          770195
Embarked         2240
dtype: int64

In [8]:
data=data.drop(columns=['PassengerId','Name','Age','Ticket','Cabin'])

In [9]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch       Fare Embarked
0         1       1  female      0      0  76.760165        C
1         0       3    male      0      0  10.193097        S
2         0       3    male      0      0  12.029416        C
3         0       3    male      0      0  13.429448        S
4         0       3    male      0      0   4.840769        C

In [10]:
data['Embarked'].value_counts()

Embarked
S    729468
C    186846
Q     81446
Name: count, dtype: int64

In [11]:
data['Embarked']=data['Embarked'].replace({'S':'Southampton','C':'Chebourge','Q':'Queenstown'})

In [12]:
data['Embarked'].value_counts()

Embarked
Southampton    729468
Chebourge      186846
Queenstown      81446
Name: count, dtype: int64

In [13]:
data.isnull().sum()

Survived       0
Pclass         0
Sex            0
SibSp          0
Parch          0
Fare           0
Embarked    2240
dtype: int64

In [14]:
data.dropna(subset=['Embarked'],inplace=True)

In [15]:
data.isnull().sum()

Survived    0
Pclass      0
Sex         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [16]:
data

        Survived  Pclass     Sex  SibSp  Parch        Fare     Embarked
0              1       1  female      0      0   76.760165    Chebourge
1              0       3    male      0      0   10.193097  Southampton
2              0       3    male      0      0   12.029416    Chebourge
3              0       3    male      0      0   13.429448  Southampton
4              0       3    male      0      0    4.840769    Chebourge
...          ...     ...     ...    ...    ...         ...          ...
999995         0       2    male      0      0   26.196512  Southampton
999996         1       1  female      0      0  102.555248  Southampton
999997         0       3    male      1      0    8.274807  Southampton
999998         0       2    male      1      0    0.000000  Southampton
999999         1       1  female      1      0   57.720316  Southampton

[997760 rows x 7 columns]

In [17]:
data.shape

(997760, 7)

In [18]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

In [19]:
data['Sex']=label.fit_transform(data['Sex'])

In [20]:
from sklearn.preprocessing import OneHotEncoder
onehot=OneHotEncoder(sparse_output=False)

In [22]:
Embarked = onehot.fit_transform(data[['Embarked']])

In [ ]:
Embarked=pd.DataFrame(Embarked,columns=onehot.get_feature_names_out())

In [ ]:
Embarked

        Embarked_Chebourge  Embarked_Queenstown  Embarked_Southampton
0                      1.0                  0.0                   0.0
1                      0.0                  0.0                   1.0
2                      1.0                  0.0                   0.0
3                      0.0                  0.0                   1.0
4                      1.0                  0.0                   0.0
...                    ...                  ...                   ...
997755                 0.0                  0.0                   1.0
997756                 0.0                  0.0                   1.0
997757                 0.0                  0.0                   1.0
997758                 0.0                  0.0                   1.0
997759                 0.0                  0.0                   1.0

[997760 rows x 3 columns]

In [ ]:
data=pd.concat([data.drop(columns=['Embarked']),Embarked],axis=1)

In [ ]:
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourge,Embarked_Queenstown,Embarked_Southampton
0,1.0,1.0,0.0,0.0,0.0,76.760165,1.0,0.0,0.0
1,0.0,3.0,1.0,0.0,0.0,10.193097,0.0,0.0,1.0
2,0.0,3.0,1.0,0.0,0.0,12.029416,1.0,0.0,0.0
3,0.0,3.0,1.0,0.0,0.0,13.429448,0.0,0.0,1.0
4,0.0,3.0,1.0,0.0,0.0,4.840769,1.0,0.0,0.0

In [ ]:
from sklearn.preprocessing import StandardScaler
scale= StandardScaler()

In [ ]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare',
       'Embarked_Chebourge', 'Embarked_Queenstown', 'Embarked_Southampton'],
      dtype='str')

In [ ]:
num_columns= ['Pclass', 'SibSp', 'Parch', 'Fare']

In [ ]:
data[num_columns]=scale.fit_transform(data[num_columns])

In [ ]:
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourge,Embarked_Queenstown,Embarked_Southampton
0,1.0,-1.568865,0.0,-0.462644,-0.469267,0.902298,1.0,0.0,0.0
1,0.0,0.824107,1.0,-0.462644,-0.469267,-0.485014,0.0,0.0,1.0
2,0.0,0.824107,1.0,-0.462644,-0.469267,-0.446744,1.0,0.0,0.0
3,0.0,0.824107,1.0,-0.462644,-0.469267,-0.417566,0.0,0.0,1.0
4,0.0,0.824107,1.0,-0.462644,-0.469267,-0.596561,1.0,0.0,0.0

In [ ]:
import pickle

In [ ]:
with open('label_encoder.pkl','wb') as file:
    pickle.dump(label,file)

In [ ]:
with open('one_Hot_Encoder.pkl','wb') as file:
    pickle.dump(onehot,file)

In [ ]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scale,file)

In [ ]:
X=data.drop(columns='Survived')

In [ ]:
y=data['Survived']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=20,random_state=42)

In [ ]:
X_train,X_valid,y_train,y_valid=train_test_split(X_train,y_train,test_size=0.2,random_state=42)

In [ ]:
import tensorflow

In [ ]:
X_train.shape

(799979, 8)

In [ ]:
X_valid.shape

(199995, 8)

model building

In [ ]:
(X_train.shape[1],)

(8,)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
model=Sequential([
 Input(shape=(X_train.shape[1],)),
 Dense(64,activation='relu'),
 Dense(32,activation='relu'),
 Dense(1,activation='sigmoid')   
])

In [ ]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,689 (10.50 KB)

 Trainable params: 2,689 (10.50 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
tensorflow.keras.losses.BinaryFocalCrossentropy

keras.src.losses.losses.BinaryFocalCrossentropy

In [ ]:
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
stoping_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [ ]:
model.fit(X_train,y_train,validation_data=(X_valid,y_valid),epochs=10,callbacks=[stoping_callback])

Epoch 1/10
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 87s 3ms/step - accuracy: 0.6167 - loss: nan - val_accuracy: 0.6176 - val_loss: nan
Epoch 2/10
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 79s 3ms/step - accuracy: 0.6167 - loss: nan - val_accuracy: 0.6176 - val_loss: nan
Epoch 3/10
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 77s 3ms/step - accuracy: 0.6167 - loss: nan - val_accuracy: 0.6176 - val_loss: nan
Epoch 4/10
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 89s 4ms/step - accuracy: 0.6167 - loss: nan - val_accuracy: 0.6176 - val_loss: nan
Epoch 5/10
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 87s 3ms/step - accuracy: 0.6167 - loss: nan - val_accuracy: 0.6176 - val_loss: nan
Epoch 6/10
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 81s 3ms/step - accuracy: 0.6167 - loss: nan - val_accuracy: 0.6176 - val_loss: nan

In [ ]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.